# Generated by Django 5.2.9 on 2025-12-18 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('party', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='elections.region')),
            ],
        ),
        migrations.CreateModel(
            name='Precinct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precinct_number', models.CharField(max_length=16)),
                ('registered_voters', models.IntegerField()),
                ('ballots_issued', models.IntegerField()),
                ('ballots_valid', models.IntegerField()),
                ('ballots_invalid', models.IntegerField()),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precincts', to='elections.territory')),
            ],
        ),
        migrations.CreateModel(
            name='VoteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='elections.candidate')),
                ('precinct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='elections.precinct')),
            ],
            options={
                'unique_together': {('precinct', 'candidate')},
            },
        ),
    ]
